#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2.1 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Wed Oct 22 00:03:01 CEST 2025
# SW Build 2729669 on Thu Dec  5 04:48:12 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 8913e63590014387a79dc879ed7b78a9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot stack_tb_behav xil_defaultlib.stack_tb -log elaborate.log"
xelab -wto 8913e63590014387a79dc879ed7b78a9 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip -L xpm --snapshot stack_tb_behav xil_defaultlib.stack_tb -log elaborate.log

