webtalk_init -webtalk_dir /home/marko/Documents/vivadoProjekti2/vivado/IM/IM/IM.sim/sim_1/behav/xsim/xsim.dir/im_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Aug 27 23:46:14 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2708876" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "LIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "cb68cfb6-36a8-4c5f-8b27-732604022055" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "5cb94b6e1fd34daa940c954e943e265d" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "338" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "EndeavourOS" -context "user_environment"
webtalk_add_data -client project -key os_release -value "EndeavourOS Linux" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 1600 Six-Core Processor" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3369.648 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "2" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.03_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "131368_KB" -context "xsim\\usage"
webtalk_transmit -clientid 343820866 -regid "" -xml /home/marko/Documents/vivadoProjekti2/vivado/IM/IM/IM.sim/sim_1/behav/xsim/xsim.dir/im_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html /home/marko/Documents/vivadoProjekti2/vivado/IM/IM/IM.sim/sim_1/behav/xsim/xsim.dir/im_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm /home/marko/Documents/vivadoProjekti2/vivado/IM/IM/IM.sim/sim_1/behav/xsim/xsim.dir/im_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
