#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jun 26 14:37:02 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim rtlsab1_tb_behav -key {Behavioral:sim_1:Functional:rtlsab1_tb} -tclbatch rtlsab1_tb.tcl -view /home/marko/vivadoProjekti/RTL1/rtlsab1_tb_behav.wcfg -log simulate.log"
xsim rtlsab1_tb_behav -key {Behavioral:sim_1:Functional:rtlsab1_tb} -tclbatch rtlsab1_tb.tcl -view /home/marko/vivadoProjekti/RTL1/rtlsab1_tb_behav.wcfg -log simulate.log

