#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jul 17 17:38:42 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto e14e918a185548899786a5ad12fdc68b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sseg_mux_behav xil_defaultlib.sseg_mux -log elaborate.log"
xelab -wto e14e918a185548899786a5ad12fdc68b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot sseg_mux_behav xil_defaultlib.sseg_mux -log elaborate.log

