#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Thu Jul 17 17:38:47 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim sseg_mux_behav -key {Behavioral:sim_1:Functional:sseg_mux} -tclbatch sseg_mux.tcl -log simulate.log"
xsim sseg_mux_behav -key {Behavioral:sim_1:Functional:sseg_mux} -tclbatch sseg_mux.tcl -log simulate.log

