#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Jun 09 20:49:04 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto c900d043797c409a977e0c3bebbffd96 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cfg_add8tb_csa_behav xil_defaultlib.cfg_add8tb_csa -log elaborate.log"
xelab -wto c900d043797c409a977e0c3bebbffd96 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot cfg_add8tb_csa_behav xil_defaultlib.cfg_add8tb_csa -log elaborate.log

