#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Tue Nov 12 13:57:11 CET 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 47e3ab23a1614126bb0a58ce6e2de027 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot au_tb_behav xil_defaultlib.au_tb -log elaborate.log"
xelab -wto 47e3ab23a1614126bb0a58ce6e2de027 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot au_tb_behav xil_defaultlib.au_tb -log elaborate.log

