#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Oct 20 17:58:33 CEST 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 89aacd2894ed4099a3e99dbc153e1f8a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot count16_tb_behav xil_defaultlib.count16_tb -log elaborate.log"
xelab -wto 89aacd2894ed4099a3e99dbc153e1f8a --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot count16_tb_behav xil_defaultlib.count16_tb -log elaborate.log

