#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jun 26 12:15:45 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 9f13825a8f134d1ca02fcbc955660e9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rtlsab1_tb_func_synth xil_defaultlib.rtlsab1_tb -log elaborate.log"
xelab -wto 9f13825a8f134d1ca02fcbc955660e9b --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot rtlsab1_tb_func_synth xil_defaultlib.rtlsab1_tb -log elaborate.log

