#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sun Nov 03 20:30:28 CET 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto ae4881026ccc44d58061ea5c837ffdfb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot kombmrz_tb_behav xil_defaultlib.kombmrz_tb -log elaborate.log"
xelab -wto ae4881026ccc44d58061ea5c837ffdfb --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot kombmrz_tb_behav xil_defaultlib.kombmrz_tb -log elaborate.log

