#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Sun Nov 03 20:30:29 CET 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim kombmrz_tb_behav -key {Behavioral:sim_1:Functional:kombmrz_tb} -tclbatch kombmrz_tb.tcl -view /home/marko/vivadoProjekti/dz2/kombmrz_tb_behav.wcfg -log simulate.log"
xsim kombmrz_tb_behav -key {Behavioral:sim_1:Functional:kombmrz_tb} -tclbatch kombmrz_tb.tcl -view /home/marko/vivadoProjekti/dz2/kombmrz_tb_behav.wcfg -log simulate.log

