#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Mon Nov 04 16:52:13 CET 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 11c18f0001f4497e937166e653c42c99 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot logickajedinica_tb_behav xil_defaultlib.logickajedinica_tb -log elaborate.log"
xelab -wto 11c18f0001f4497e937166e653c42c99 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot logickajedinica_tb_behav xil_defaultlib.logickajedinica_tb -log elaborate.log

