#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Aug 29 10:35:18 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xsim im_tb_behav -key {Behavioral:sim_1:Functional:im_tb} -tclbatch im_tb.tcl -view /home/marko/Documents/vivadoProjekti2/vivado/IM/im_tb_behav.wcfg -log simulate.log"
xsim im_tb_behav -key {Behavioral:sim_1:Functional:im_tb} -tclbatch im_tb.tcl -view /home/marko/Documents/vivadoProjekti2/vivado/IM/im_tb_behav.wcfg -log simulate.log

