#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Fri Jul 25 14:45:16 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 3a75ebd602b14c8d8ba1c42b86121caa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot receiver_tb_behav xil_defaultlib.receiver_tb -log elaborate.log"
xelab -wto 3a75ebd602b14c8d8ba1c42b86121caa --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot receiver_tb_behav xil_defaultlib.receiver_tb -log elaborate.log

