#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Sat Dec 07 11:53:02 CET 2024
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto bb7207f782b146ddabe95af3fccee09c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot automat1_tb_behav xil_defaultlib.automat1_tb -log elaborate.log"
xelab -wto bb7207f782b146ddabe95af3fccee09c --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot automat1_tb_behav xil_defaultlib.automat1_tb -log elaborate.log

