#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2019.2 (64-bit)
#
# Filename    : elaborate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for elaborating the compiled design
#
# Generated by Vivado on Thu Jun 26 00:10:55 CEST 2025
# SW Build 2708876 on Wed Nov  6 21:39:14 MST 2019
#
# Copyright 1986-2019 Xilinx, Inc. All Rights Reserved.
#
# usage: elaborate.sh
#
# ****************************************************************************
set -Eeuo pipefail
echo "xelab -wto 040a0f96e9bf4fd481a82ca2a28def26 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot shift_reg2tb_behav xil_defaultlib.shift_reg2tb -log elaborate.log"
xelab -wto 040a0f96e9bf4fd481a82ca2a28def26 --incr --debug typical --relax --mt 8 -L xil_defaultlib -L secureip --snapshot shift_reg2tb_behav xil_defaultlib.shift_reg2tb -log elaborate.log

